### ISSUE TITLE
nvim里面lsp的sumneko_lua好像官方换名字成lua_ls了

### ISSUE THREAD

**Issue by MonostableLSD** [ZyWCN1998/MyDevEnvFile#1]
大佬好，在使用过程发现问题rt

**Comment by ZyWCN1998** [comment]
好的，抱歉最近实验量比较大，折腾这些的时间少了很多，你可以提一个pull request，谢谢啦

**Comment by ZyWCN1998** [comment]
修改了一下lspconfig.lua和mason.lua里"sumneko_lua"->"lua_ls"应该就可以了。我注意到[josean](https://github.com/josean-dev/dev-environment-files/commits?author=josean-dev)的文件也改了
